[build]
  command = "ng build --localize"
  publish = "dist"

[[redirects]]
  from = "/cy/*"
  to = "/cy/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/en-US/index.html"
  status = 200
